pythonVersion: 3.10
services:
  - type: web
    name: stock-prediction-app
    runtime: python
    pythonVersion: 3.10
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run Trading_App.py --server.port=$PORT --server.enableCORS=false